{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "e32c9505",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<Response [200]>\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import requests as req\n",
    "\n",
    "url = 'https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_population'\n",
    "\n",
    "test_url = 'https://api.github.com/repos/pandas-dev/pandas/issues'\n",
    "\n",
    "resp = req.get(url)\n",
    "test_resp = req.get(test_url)\n",
    "\n",
    "resp.raise_for_status()\n",
    "\n",
    "print(resp)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "71efb47f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62174', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62174/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62174/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62174/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62174', 'id': 3347012226, 'node_id': 'PR_kwDOAA0YD86k9-h6', 'number': 62174, 'title': 'BUG/TST: Series round with dtype object', 'user': {'login': 'sharkipelago', 'id': 49359843, 'node_id': 'MDQ6VXNlcjQ5MzU5ODQz', 'avatar_url': 'https://avatars.githubusercontent.com/u/49359843?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sharkipelago', 'html_url': 'https://github.com/sharkipelago', 'followers_url': 'https://api.github.com/users/sharkipelago/followers', 'following_url': 'https://api.github.com/users/sharkipelago/following{/other_user}', 'gists_url': 'https://api.github.com/users/sharkipelago/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sharkipelago/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sharkipelago/subscriptions', 'organizations_url': 'https://api.github.com/users/sharkipelago/orgs', 'repos_url': 'https://api.github.com/users/sharkipelago/repos', 'events_url': 'https://api.github.com/users/sharkipelago/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sharkipelago/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-22T22:56:55Z', 'updated_at': '2025-08-22T22:59:16Z', 'closed_at': None, 'author_association': 'CONTRIBUTOR', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62174', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62174', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62174.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62174.patch', 'merged_at': None}, 'body': \"- [x] addresses pointwise behavior talked about discussed in #61682 with @jbrockmendel \\r\\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\\r\\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\\r\\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\\r\\n\\r\\nI changed the behavior or series.round() to act like `series.map(round)` if the dtype is object as discussed in #61682. I put this in a new PR as the original intent of the other PR was to change DataFrame behavior. I'm unsure if the way I approached it is a good way to make the change though because I saw in `core/internals/blocks.py` that `Block`'s `round()` method is intended to raise an error for dtype of object. So I wasn't sure I should approach this by updated the `Block` class instead. Any feedback is appreciated!\\r\\n\", 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62174/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62174/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62172', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62172/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62172/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62172/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62172', 'id': 3345771731, 'node_id': 'PR_kwDOAA0YD86k5q4h', 'number': 62172, 'title': \"DOC: update the description for the 'docker build' command\", 'user': {'login': 'tihanayo', 'id': 221698895, 'node_id': 'U_kgDODTbbTw', 'avatar_url': 'https://avatars.githubusercontent.com/u/221698895?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/tihanayo', 'html_url': 'https://github.com/tihanayo', 'followers_url': 'https://api.github.com/users/tihanayo/followers', 'following_url': 'https://api.github.com/users/tihanayo/following{/other_user}', 'gists_url': 'https://api.github.com/users/tihanayo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/tihanayo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/tihanayo/subscriptions', 'organizations_url': 'https://api.github.com/users/tihanayo/orgs', 'repos_url': 'https://api.github.com/users/tihanayo/repos', 'events_url': 'https://api.github.com/users/tihanayo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/tihanayo/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 1, 'created_at': '2025-08-22T14:59:03Z', 'updated_at': '2025-08-22T19:13:58Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62172', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62172', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62172.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62172.patch', 'merged_at': None}, 'body': '- [x] closes #61037 (Replace xxxx with the GitHub issue number)\\r\\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\\r\\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\\r\\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\\r\\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\\r\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62172/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62172/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62169', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62169/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62169/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62169/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62169', 'id': 3343555956, 'node_id': 'I_kwDOAA0YD87HSp10', 'number': 62169, 'title': 'BUG: Index.get_level_values() does not handle boolean, pd.NA, np.nan, or pd.NaT `level` correctly', 'user': {'login': 'sfc-gh-mvashishtha', 'id': 149194323, 'node_id': 'U_kgDOCOSGUw', 'avatar_url': 'https://avatars.githubusercontent.com/u/149194323?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/sfc-gh-mvashishtha', 'html_url': 'https://github.com/sfc-gh-mvashishtha', 'followers_url': 'https://api.github.com/users/sfc-gh-mvashishtha/followers', 'following_url': 'https://api.github.com/users/sfc-gh-mvashishtha/following{/other_user}', 'gists_url': 'https://api.github.com/users/sfc-gh-mvashishtha/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/sfc-gh-mvashishtha/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/sfc-gh-mvashishtha/subscriptions', 'organizations_url': 'https://api.github.com/users/sfc-gh-mvashishtha/orgs', 'repos_url': 'https://api.github.com/users/sfc-gh-mvashishtha/repos', 'events_url': 'https://api.github.com/users/sfc-gh-mvashishtha/events{/privacy}', 'received_events_url': 'https://api.github.com/users/sfc-gh-mvashishtha/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 1, 'created_at': '2025-08-21T23:52:04Z', 'updated_at': '2025-08-22T01:14:03Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': \"### Pandas version checks\\n\\n- [x] I have checked that this issue has not already been reported.\\n\\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\\n\\n- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\\n\\n\\n### Reproducible Example\\n\\n```python\\nimport pandas as pd\\npd.Index([], name=True).get_level_values(level=True)\\n```\\n\\n### Issue Description\\n\\nI get `IndexError: Too many levels: Index has only 1 level, not 2`. Also, ` pd.Index([], name=True).get_level_values(level=False)` should raise `KeyError`, but it returns the whole index.\\n\\nAlso, name `np.nan`, `pd.NA` or `pd.NaT` causes ` KeyError: 'Requested level (nan) does not match index name (nan)'`.\\n\\n### Expected Behavior\\n\\nI should get the whole index from `get_level_values(True)`\\n\\n### Installed Versions\\n\\n<details>\\n\\n------------------\\ncommit                : 4665c10899bc413b639194f6fb8665a5c70f7db5\\npython                : 3.13.5\\npython-bits           : 64\\nOS                    : Darwin\\nOS-release            : 24.6.0\\nVersion               : Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:30 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T6020\\nmachine               : arm64\\nprocessor             : arm\\nbyteorder             : little\\nLC_ALL                : None\\nLANG                  : en_US.UTF-8\\nLOCALE                : en_US.UTF-8\\n\\npandas                : 2.3.2\\nnumpy                 : 2.3.2\\npytz                  : 2025.2\\ndateutil              : 2.9.0.post0\\npip                   : 25.1\\nCython                : None\\nsphinx                : None\\nIPython               : 9.4.0\\nadbc-driver-postgresql: None\\nadbc-driver-sqlite    : None\\nbs4                   : None\\nblosc                 : None\\nbottleneck            : None\\ndataframe-api-compat  : None\\nfastparquet           : None\\nfsspec                : None\\nhtml5lib              : None\\nhypothesis            : None\\ngcsfs                 : None\\njinja2                : None\\nlxml.etree            : None\\nmatplotlib            : None\\nnumba                 : None\\nnumexpr               : None\\nodfpy                 : None\\nopenpyxl              : None\\npandas_gbq            : None\\npsycopg2              : None\\npymysql               : None\\npyarrow               : None\\npyreadstat            : None\\npytest                : None\\npython-calamine       : None\\npyxlsb                : None\\ns3fs                  : None\\nscipy                 : None\\nsqlalchemy            : None\\ntables                : None\\ntabulate              : None\\nxarray                : None\\nxlrd                  : None\\nxlsxwriter            : None\\nzstandard             : None\\ntzdata                : 2025.2\\nqtpy                  : None\\npyqt5                 : None\\n\\n</details>\\n\", 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62169/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62169/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62164', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62164/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62164/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62164/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62164', 'id': 3341927427, 'node_id': 'I_kwDOAA0YD87HMcQD', 'number': 62164, 'title': 'REF: use _cast_pointwise_result in map', 'user': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-21T14:13:42Z', 'updated_at': '2025-08-21T14:13:42Z', 'closed_at': None, 'author_association': 'MEMBER', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': 'Recently implemented _cast_pointwise_result is the correct idiom to use to retain dtype_backend in EA.map and any similar ops.', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62164/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62164/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62162', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62162/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62162/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62162/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62162', 'id': 3339878599, 'node_id': 'PR_kwDOAA0YD86klwz0', 'number': 62162, 'title': 'CLN: Replace warnings with Pandas4Warning', 'user': {'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-21T00:26:34Z', 'updated_at': '2025-08-22T16:19:37Z', 'closed_at': None, 'author_association': 'MEMBER', 'type': None, 'active_lock_reason': None, 'draft': True, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62162', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62162', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62162.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62162.patch', 'merged_at': None}, 'body': '- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\\r\\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\\r\\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\\r\\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\\r\\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\\r\\n\\r\\nReplaces all appropriate FutureWarnings and DeprecationWarnings with Pandas4Warnings. For those that are to be enforced in 3.0, I added `# TODO: Enforce ...`. I plan to introduce linting rules on FutureWarning/DeprecationWarning next.', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62162/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62162/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62161', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62161/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62161/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62161/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62161', 'id': 3339837083, 'node_id': 'I_kwDOAA0YD87HEd6b', 'number': 62161, 'title': 'DOC: date_range/timedelta_range confusing 3 out of 4 arguments note', 'user': {'login': 'loicdiridollou', 'id': 52484416, 'node_id': 'MDQ6VXNlcjUyNDg0NDE2', 'avatar_url': 'https://avatars.githubusercontent.com/u/52484416?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/loicdiridollou', 'html_url': 'https://github.com/loicdiridollou', 'followers_url': 'https://api.github.com/users/loicdiridollou/followers', 'following_url': 'https://api.github.com/users/loicdiridollou/following{/other_user}', 'gists_url': 'https://api.github.com/users/loicdiridollou/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/loicdiridollou/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/loicdiridollou/subscriptions', 'organizations_url': 'https://api.github.com/users/loicdiridollou/orgs', 'repos_url': 'https://api.github.com/users/loicdiridollou/repos', 'events_url': 'https://api.github.com/users/loicdiridollou/events{/privacy}', 'received_events_url': 'https://api.github.com/users/loicdiridollou/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-20T23:57:56Z', 'updated_at': '2025-08-21T00:36:49Z', 'closed_at': None, 'author_association': 'MEMBER', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': '### Pandas version checks\\n\\n- [x] I have checked that the issue still exists on the latest versions of the docs on `main` [here](https://pandas.pydata.org/docs/dev/)\\n\\n\\n### Location of the documentation\\n\\nhttps://pandas.pydata.org/docs/dev/reference/api/pandas.date_range.html#pandas.date_range\\nhttps://pandas.pydata.org/docs/dev/reference/api/pandas.timedelta_range.html\\n\\n### Documentation problem\\n\\nWe are trying to improve the type hinting for those two functions in `pandas-stubs` repo.\\nCurrently the note in both those functions mentions that we should specify 3 out of 4 arguments among `start`, `end`, `period`, `freq`.\\nHowever it seems like the usage (even in the examples) one can specify only 2 of the arguments like start and end. After looking at the code, it seems like `freq` even if none gets converted to `D`.\\n\\n### Suggested fix for documentation\\n\\nI believe we should specify two out of three `start`, `end`, `periods` and never all four together. Rephrasing from three out of four but if freq is omitted then ... would help clarify the goal.\\n\\nHere would be a possible version:\\n\\n```\\nOf the four parameters start, end, periods, and freq, between two and three must be specified. If freq is omitted,\\n the resulting TimedeltaIndex will have periods linearly spaced elements between start and end (closed on both\\n sides) using a day increment.\\n```', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62161/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62161/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62159', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62159/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62159/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62159/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62159', 'id': 3339722814, 'node_id': 'PR_kwDOAA0YD86klQF8', 'number': 62159, 'title': 'DEPR: .str accessor with object dtype', 'user': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-20T22:38:35Z', 'updated_at': '2025-08-20T22:38:35Z', 'closed_at': None, 'author_association': 'MEMBER', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62159', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62159', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62159.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62159.patch', 'merged_at': None}, 'body': '- [x] closes #29710 (Replace xxxx with the GitHub issue number)\\r\\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\\r\\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\\r\\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\\r\\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\\r\\n\\r\\nThere are two cases we need an answer for before merging this.  One, as I just posted in #29710\\r\\n\\r\\n> looking at doing this, the main problem is .decode. For everything else we can tell users to do obj.astype(\"str\").str, but if you have bytes to start out with, that doesn\\'t work. Unless we assume pyarrow is available and then can tell users to do .astype(\"bytes[pyarrow]\").str.decode\\r\\n\\r\\nThe other is when you can\\'t cast to \"str\" bc you have funky entries, like in  test_to_hdf_errors `data = [\"\\\\ud800foo\"]`.', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62159/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62159/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62158', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62158/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62158/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62158/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62158', 'id': 3339672171, 'node_id': 'I_kwDOAA0YD87HD1pr', 'number': 62158, 'title': 'API: indexing dates-with-datetime64', 'user': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 1, 'created_at': '2025-08-20T22:07:16Z', 'updated_at': '2025-08-21T05:32:18Z', 'closed_at': None, 'author_association': 'MEMBER', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': '### Pandas version checks\\n\\n- [x] I have checked that this issue has not already been reported.\\n\\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\\n\\n- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\\n\\n\\n### Reproducible Example\\n\\n```python\\nser = pd.Series([\"2016-01-01\"], dtype=\"date32[pyarrow]\")\\nser2 = ser.astype(\"timestamp[ns][pyarrow]\")\\nser3 = ser.astype(\"datetime64[ns]\")\\n\\ndti = pd.Index(ser3)\\ndti.get_loc(ser[0])  # raises KeyError\\ndti.get_indexer(ser.values)  # -1s\\ndti.get_indexer(ser.values.astype(object))  # 0s; inconsistent\\n```\\n\\n### Issue Description\\n\\nDatetimeIndex.get_indexer has a special case (actually in Index._maybe_downcast_for_indexing) for sequences of `date` objects that is inconsistent with both scalar treatment and comparison op behavior.  This was mostly benign before the existence of a date dtype, but now has the potential to cause problems.  The special case should be deprecated.\\n\\n### Expected Behavior\\n\\nNA\\n\\n### Installed Versions\\n\\n<details>\\n\\nReplace this line with the output of pd.show_versions()\\n\\n</details>\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62158/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62158/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62157', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62157/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62157/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62157/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62157', 'id': 3339661943, 'node_id': 'I_kwDOAA0YD87HDzJ3', 'number': 62157, 'title': 'BUG/API: comparison datetime64-vs-dates', 'user': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-20T22:02:13Z', 'updated_at': '2025-08-20T22:02:28Z', 'closed_at': None, 'author_association': 'MEMBER', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': '```python\\nser = pd.Series([\"2016-01-01\"], dtype=\"date32[pyarrow]\")\\nser2 = ser.astype(\"timestamp[ns][pyarrow]\")\\nser3 = ser.astype(\"datetime64[ns]\")\\n\\nassert (ser3 != ser[0]).all()\\nassert (ser3 != ser).all()\\n\\nassert (ser == ser3).all()  # <- uh-oh! inconsistent with reversed operation\\nassert (ser == ser2).all()  # inconsistent with the non-pyarrow behavior\\nassert (ser2 == ser).all()\\n```\\n\\n\\nLong ago we made a decision that datetime64 arrays (and Timestamp) were _not_ comparable to date objects, matching the stdlib behavior.  We should have that behavior for pyarrow dtypes too.\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62157/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62157/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62154', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62154/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62154/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62154/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62154', 'id': 3337920434, 'node_id': 'I_kwDOAA0YD87G9J-y', 'number': 62154, 'title': 'BUG: resampling with origin=end_date includes extra elements in the bucket', 'user': {'login': 'vasil-pashov', 'id': 6077479, 'node_id': 'MDQ6VXNlcjYwNzc0Nzk=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6077479?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/vasil-pashov', 'html_url': 'https://github.com/vasil-pashov', 'followers_url': 'https://api.github.com/users/vasil-pashov/followers', 'following_url': 'https://api.github.com/users/vasil-pashov/following{/other_user}', 'gists_url': 'https://api.github.com/users/vasil-pashov/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/vasil-pashov/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/vasil-pashov/subscriptions', 'organizations_url': 'https://api.github.com/users/vasil-pashov/orgs', 'repos_url': 'https://api.github.com/users/vasil-pashov/repos', 'events_url': 'https://api.github.com/users/vasil-pashov/events{/privacy}', 'received_events_url': 'https://api.github.com/users/vasil-pashov/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-20T12:21:22Z', 'updated_at': '2025-08-20T12:21:22Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': '### Pandas version checks\\n\\n- [x] I have checked that this issue has not already been reported.\\n\\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\\n\\n- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\\n\\n\\n### Reproducible Example\\n\\n```python\\nimport pandas as pd\\nfrom pandas import Timedelta, Timestamp\\ndf = pd.DataFrame({\"col\": [1, 2]}, index=pd.to_datetime([\"1969-06-01 00:00:00.000000000\",\"1969-06-01 02:01:00.000000001\"]))\\nrule = \"7315s\"\\noffset = pd.Timedelta(\"23min\")\\ndf.resample(rule, origin=\"end_day\", offset=offset, closed=\"right\", label=\"left\").agg(None, col_first=(\"col\", \"first\"), col_count=(\"col\", \"count\"))\\n\\n\\nThis outputs\\n\\n\\tcol_first\\tcol_count\\n1969-06-01\\t1\\t2\\n```\\n\\n### Issue Description\\n\\nThe bucket starting at `1969-06-01` should not include the first row from the dataframe. The index is `1969-06-01 00:00:00.000000000` and closed is `right` which means that the value is on the opened boundary thus it does not fall into the bucket.\\n\\nMoreover if the second row is removed we get\\n```python\\nimport pandas as pd\\nfrom pandas import Timedelta, Timestamp\\ndf = pd.DataFrame({\"col\": [1]}, index=pd.to_datetime([\"1969-06-01 00:00:00.000000000\"]))\\nrule = \"7315s\"\\noffset = pd.Timedelta(\"23min\")\\ndf.resample(rule, origin=\"end_day\", offset=offset, closed=\"right\", label=\"left\").agg(None, col_first=(\"col\", \"first\"), col_count=(\"col\", \"count\"))\\n```\\nWhich outputs:\\n```\\tcol_first\\tcol_count\\n1969-05-31 22:21:05\\t1\\t1\\n```\\n\\n### Expected Behavior\\n\\n```python\\nimport pandas as pd\\nfrom pandas import Timedelta, Timestamp\\ndf = pd.DataFrame({\"col\": [1, 2]}, index=pd.to_datetime([\"1969-06-01 00:00:00.000000000\",\"1969-06-01 02:01:00.000000001\"]))\\nrule = \"7315s\"\\noffset = pd.Timedelta(\"23min\")\\ndf.resample(rule, origin=\"end_day\", offset=offset, closed=\"right\", label=\"left\").agg(None, col_first=(\"col\", \"first\"), col_count=(\"col\", \"count\"))\\n```\\nThe first row should not be part of the bucket. It\\'s part of the bucket starting at `1969-05-31 22:21:05` but as this is before the first value of the dataframe that bucket is not created.\\n```\\n\\tcol_first\\tcol_count\\n1969-06-01\\t2\\t1\\n```\\n\\n### Installed Versions\\n\\n<details>\\n\\nINSTALLED VERSIONS\\n------------------\\ncommit                : c888af6d0bb674932007623c0867e1fbd4bdc2c6\\npython                : 3.11.2\\npython-bits           : 64\\nOS                    : Linux\\nOS-release            : 6.1.0-38-amd64\\nVersion               : #1 SMP PREEMPT_DYNAMIC Debian 6.1.147-1 (2025-08-02)\\nmachine               : x86_64\\nprocessor             : \\nbyteorder             : little\\nLC_ALL                : None\\nLANG                  : en_US.UTF-8\\nLOCALE                : en_US.UTF-8\\n\\npandas                : 2.3.1\\nnumpy                 : 1.26.4\\npytz                  : 2025.2\\ndateutil              : 2.9.0.post0\\npip                   : 25.2\\nCython                : None\\nsphinx                : None\\nIPython               : 9.3.0\\nadbc-driver-postgresql: None\\nadbc-driver-sqlite    : None\\nbs4                   : 4.13.4\\nblosc                 : None\\nbottleneck            : None\\ndataframe-api-compat  : None\\nfastparquet           : None\\nfsspec                : None\\nhtml5lib              : None\\nhypothesis            : 6.72.4\\ngcsfs                 : None\\njinja2                : 3.1.6\\nlxml.etree            : None\\nmatplotlib            : None\\nnumba                 : None\\nnumexpr               : None\\nodfpy                 : None\\nopenpyxl              : None\\npandas_gbq            : None\\npsycopg2              : None\\npymysql               : None\\npyarrow               : 21.0.0\\npyreadstat            : None\\npytest                : 8.4.0\\npython-calamine       : None\\npyxlsb                : None\\ns3fs                  : None\\nscipy                 : None\\nsqlalchemy            : None\\ntables                : None\\ntabulate              : 0.9.0\\nxarray                : None\\nxlrd                  : None\\nxlsxwriter            : None\\nzstandard             : None\\ntzdata                : 2025.2\\nqtpy                  : None\\npyqt5                 : None\\n</details>\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62154/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62154/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62150', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62150/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62150/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62150/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62150', 'id': 3336294818, 'node_id': 'I_kwDOAA0YD87G29Gi', 'number': 62150, 'title': 'BUG: Inconsistent behaviour when merging reset-ed MultiIndex dataframe', 'user': {'login': 'renkeven', 'id': 15991811, 'node_id': 'MDQ6VXNlcjE1OTkxODEx', 'avatar_url': 'https://avatars.githubusercontent.com/u/15991811?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/renkeven', 'html_url': 'https://github.com/renkeven', 'followers_url': 'https://api.github.com/users/renkeven/followers', 'following_url': 'https://api.github.com/users/renkeven/following{/other_user}', 'gists_url': 'https://api.github.com/users/renkeven/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/renkeven/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/renkeven/subscriptions', 'organizations_url': 'https://api.github.com/users/renkeven/orgs', 'repos_url': 'https://api.github.com/users/renkeven/repos', 'events_url': 'https://api.github.com/users/renkeven/events{/privacy}', 'received_events_url': 'https://api.github.com/users/renkeven/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-20T01:55:34Z', 'updated_at': '2025-08-20T01:55:34Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': '### Pandas version checks\\n\\n- [x] I have checked that this issue has not already been reported.\\n\\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\\n\\n- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\\n\\n\\n### Reproducible Example\\n\\n```python\\ndf = pd.DataFrame(data={(\"column_1\", \"\"): [1,1], (\"column_2\", \"\"): [2,2]})\\ndf.index = pd.MultiIndex.from_arrays([[1,1], [\"metadata_1\", \"metadata_2\"]], names=[\"index\", \"metadata\"])\\n\\ndf2 = pd.DataFrame(data=[1,1], index=[1,1]).rename_axis(\"index\", axis=0)\\ndf2.columns = pd.MultiIndex.from_product([[\"new_data\"], [\"\"]])\\n\\ndf.reset_index().merge(df2.reset_index(), on=\"index\")\\n# IndexError: Requested axis not found in manager\\n\\ndf.reset_index().merge(df2.reset_index(), on=[(\"index\", \"\")])\\n# IndexError: Requested axis not found in manager\\n\\ndf.reset_index().columns\\n# MultiIndex([(   \\'index\\', \\'\\'),\\n#             (\\'metadata\\', \\'\\'),\\n#             (\\'column_1\\', \\'\\'),\\n#             (\\'column_2\\', \\'\\')],\\n#            )\\n\\ndf2.reset_index().columns\\n# MultiIndex([(   \\'index\\', \\'\\'),\\n#             (\\'new_data\\', \\'\\')],\\n#            )\\n\\n## We have a workaround if we force df2 to start as a multi-index, then it works\\ndf2 = pd.DataFrame(data=[1,1], index=[1,1]).rename_axis(\"index\", axis=0)\\ndf2.columns = pd.MultiIndex.from_product([[\"new_data\"], [\"\"]])\\ndf2.index = pd.MultiIndex.from_arrays(\\n        [df2.index, [\"dummy\"] * len(df2)],\\n        names=[\"index\", \"dummy_index\"],\\n    )\\n\\n# Merge works\\ndf.reset_index().merge(df2.reset_index(), on=[(\"index\", \"\")])\\n\\n# Extra empty multi-index column\\ndf2.reset_index().columns\\n# MultiIndex([(   \\'index\\', \\'\\'),\\n#            (\\'dummy_index\\', \\'\\'),\\n#            (\\'new_data\\', \\'\\')],\\n#           )\\n```\\n\\n### Issue Description\\n\\nI have a dataframe (main) with multi-indexed index and columns. I would like to do a merge with a second dataframe (side) that is single-index and single column.\\n\\nI coerced (side) to give it the same levels in the columns, and do a pd.merge on (main).reset_index and side.reset_index.\\n\\nThe example works if you make (side) also a multi-index index.\\n\\nAdditionally, the first example above is fine on 2.2.3, but is broken on 2.3.1\\n\\n\\n\\n### Expected Behavior\\n\\nUsual merge behaviour. Not sure why the initial dataframe must both have multi-index indexes when we use .reset_index() on both and merge over a single column\\n\\n### Installed Versions\\n\\n<details>\\n\\n\\nINSTALLED VERSIONS\\n------------------\\ncommit                : c888af6d0bb674932007623c0867e1fbd4bdc2c6\\npython                : 3.12.11\\npython-bits           : 64\\nOS                    : Linux\\nOS-release            : 6.6.93+\\nVersion               : #1 SMP PREEMPT_DYNAMIC Fri Jun 27 09:03:39 UTC 2025\\nmachine               : x86_64\\nprocessor             : x86_64\\nbyteorder             : little\\nLC_ALL                : en_US.UTF-8\\nLANG                  : en_US.UTF-8\\nLOCALE                : en_US.UTF-8\\n\\npandas                : 2.3.1\\nnumpy                 : 1.26.4\\npytz                  : 2024.1\\ndateutil              : 2.9.0.post0\\npip                   : 25.0.1\\nCython                : None\\nsphinx                : None\\nIPython               : 8.36.0\\nadbc-driver-postgresql: None\\nadbc-driver-sqlite    : None\\nbs4                   : 4.13.4\\nblosc                 : None\\nbottleneck            : None\\ndataframe-api-compat  : None\\nfastparquet           : None\\nfsspec                : 2025.3.2\\nhtml5lib              : None\\nhypothesis            : None\\ngcsfs                 : 2025.3.2\\njinja2                : 3.1.6\\nlxml.etree            : 6.0.0\\nmatplotlib            : 3.10.5\\nnumba                 : 0.61.2\\nnumexpr               : None\\nodfpy                 : None\\nopenpyxl              : 3.1.5\\npandas_gbq            : None\\npsycopg2              : 2.9.9\\npymysql               : None\\npyarrow               : 19.0.1\\npyreadstat            : None\\npytest                : 8.3.5\\npython-calamine       : None\\npyxlsb                : 1.0.10\\ns3fs                  : None\\nscipy                 : 1.16.0\\nsqlalchemy            : 2.0.42\\ntables                : None\\ntabulate              : 0.9.0\\nxarray                : 2025.1.2\\nxlrd                  : 2.0.1\\nxlsxwriter            : 3.2.3\\nzstandard             : 0.23.0\\ntzdata                : 2025.2\\nqtpy                  : None\\npyqt5                 : None\\n\\n</details>\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62150/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62150/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62149', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62149/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62149/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62149/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62149', 'id': 3335764167, 'node_id': 'PR_kwDOAA0YD86kXzPN', 'number': 62149, 'title': 'REF: get rid of StringArrayNumpySemantics', 'user': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-19T21:35:50Z', 'updated_at': '2025-08-22T17:05:02Z', 'closed_at': None, 'author_association': 'MEMBER', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62149', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62149', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62149.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62149.patch', 'merged_at': None}, 'body': 'xref #62129 get one less variant', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62149/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62149/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62146', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62146/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62146/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62146/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62146', 'id': 3335038521, 'node_id': 'I_kwDOAA0YD87GyKY5', 'number': 62146, 'title': 'BUG: Fails to Build on Raspberry Pi 3 (tested both 2.1.4, 2.3.1 and main Branch)', 'user': {'login': 'luckylinux', 'id': 7126291, 'node_id': 'MDQ6VXNlcjcxMjYyOTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/7126291?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/luckylinux', 'html_url': 'https://github.com/luckylinux', 'followers_url': 'https://api.github.com/users/luckylinux/followers', 'following_url': 'https://api.github.com/users/luckylinux/following{/other_user}', 'gists_url': 'https://api.github.com/users/luckylinux/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/luckylinux/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/luckylinux/subscriptions', 'organizations_url': 'https://api.github.com/users/luckylinux/orgs', 'repos_url': 'https://api.github.com/users/luckylinux/repos', 'events_url': 'https://api.github.com/users/luckylinux/events{/privacy}', 'received_events_url': 'https://api.github.com/users/luckylinux/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 1, 'created_at': '2025-08-19T16:49:22Z', 'updated_at': '2025-08-19T17:51:28Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': '### Pandas version checks\\n\\n- [x] I have checked that this issue has not already been reported.\\n\\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\\n\\n- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\\n\\n\\n### Reproducible Example\\n\\n```python\\nBuild Fails on Raspberry Pi 3 running Raspberry Pi OS based on Debian Trixie (13) on ARMHF (32 Bit Mode).\\n```\\n\\n### Issue Description\\n\\nEverything was working fine on Debian Boorworm (12) ARMHF on a Raspberry Pi 3.\\n\\nWhen I decided to upgrade today to Debian Trixie (13) ARMHF, I had to create a new `venv` since Python changed from Version 3.11 to 3.13.\\n\\nUnfortunately, I couldn\\'t build `pandas` at all 😞.\\n\\nAnd, despite the Claims in the Error Message, there is no Log File at all about why Meson failed to build.\\n\\n### Expected Behavior\\n\\nBuild should succeed and I should be able to use `pandas` within my Python Application.\\n\\n### Installed Versions\\n\\nCannot build/install.\\n\\nTried 2.3.1 which is latest:\\n```\\nLooking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple\\nRequirement already satisfied: python-can in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 1)) (4.6.1)\\nCollecting pandas (from -r requirements.txt (line 2))\\n  Using cached pandas-2.3.1.tar.gz (4.5 MB)\\n  Installing build dependencies ... done\\n  Getting requirements to build wheel ... done\\n  Installing backend dependencies ... done\\n  Preparing metadata (pyproject.toml) ... error\\n  error: subprocess-exited-with-error\\n  \\n  × Preparing metadata (pyproject.toml) did not run successfully.\\n  │ exit code: 1\\n  ╰─> [31 lines of output]\\n      + meson setup /tmp/pip-install-y9j9k_v2/pandas_d677fcd2c13643ff8c24a90c0a9f811f /tmp/pip-install-y9j9k_v2/pandas_d677fcd2c13643ff8c24a90c0a9f811f/.mesonpy-uutfurzj -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-y9j9k_v2/pandas_d677fcd2c13643ff8c24a90c0a9f811f/.mesonpy-uutfurzj/meson-python-native-file.ini\\n      The Meson build system\\n      Version: 1.8.3\\n      Source dir: /tmp/pip-install-y9j9k_v2/pandas_d677fcd2c13643ff8c24a90c0a9f811f\\n      Build dir: /tmp/pip-install-y9j9k_v2/pandas_d677fcd2c13643ff8c24a90c0a9f811f/.mesonpy-uutfurzj\\n      Build type: native build\\n      Project name: pandas\\n      Project version: 2.3.1\\n      C compiler for the host machine: cc (gcc 14.2.0 \"cc (Raspbian 14.2.0-19+rpi1) 14.2.0\")\\n      C linker for the host machine: cc ld.bfd 2.44\\n      C++ compiler for the host machine: c++ (gcc 14.2.0 \"c++ (Raspbian 14.2.0-19+rpi1) 14.2.0\")\\n      C++ linker for the host machine: c++ ld.bfd 2.44\\n      Cython compiler for the host machine: cython (cython 3.1.3)\\n      Host machine cpu family: arm\\n      Host machine cpu: armv7l\\n      Program python found: YES (/opt/app/venv/bin/python)\\n      \\n      ../pandas/meson.build:1:15: ERROR: Command `/opt/app/venv/bin/python -c \\'\\n      import os\\n      import numpy as np\\n      try:\\n          # Check if include directory is inside the pandas dir\\n          # e.g. a venv created inside the pandas dir\\n          # If so, convert it to a relative path\\n          incdir = os.path.relpath(np.get_include())\\n      except Exception:\\n          incdir = np.get_include()\\n      print(incdir)\\n           \\'` failed with status 1.\\n      \\n      A full log can be found at /tmp/pip-install-y9j9k_v2/pandas_d677fcd2c13643ff8c24a90c0a9f811f/.mesonpy-uutfurzj/meson-logs/meson-log.txt\\n      [end of output]\\n  \\n  note: This error originates from a subprocess, and is likely not a problem with pip.\\nerror: metadata-generation-failed\\n\\n× Encountered error while generating package metadata.\\n╰─> See above for output.\\n\\nnote: This is an issue with the package mentioned above, not pip.\\nhint: See above for details.\\n```\\n\\nTried 2.1.4 which worked fine on Debian Bookworm:\\n```\\nLooking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple\\nRequirement already satisfied: python-can==4.3.1 in ./venv/lib/python3.13/site-packages (from -r requirements.txt (line 1)) (4.3.1)\\nCollecting pandas==2.1.4 (from -r requirements.txt (line 2))\\n  Downloading pandas-2.1.4.tar.gz (4.3 MB)\\n     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 6.6 MB/s  0:00:00\\n  Installing build dependencies ... done\\n  Getting requirements to build wheel ... done\\n  Installing backend dependencies ... done\\n  Preparing metadata (pyproject.toml) ... error\\n  error: subprocess-exited-with-error\\n  \\n  × Preparing metadata (pyproject.toml) did not run successfully.\\n  │ exit code: 1\\n  ╰─> [31 lines of output]\\n      + meson setup /tmp/pip-install-lpm0348t/pandas_049cc42ad8234edf931488590a6d6657 /tmp/pip-install-lpm0348t/pandas_049cc42ad8234edf931488590a6d6657/.mesonpy-lko771pl/build -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-lpm0348t/pandas_049cc42ad8234edf931488590a6d6657/.mesonpy-lko771pl/build/meson-python-native-file.ini\\n      The Meson build system\\n      Version: 1.2.1\\n      Source dir: /tmp/pip-install-lpm0348t/pandas_049cc42ad8234edf931488590a6d6657\\n      Build dir: /tmp/pip-install-lpm0348t/pandas_049cc42ad8234edf931488590a6d6657/.mesonpy-lko771pl/build\\n      Build type: native build\\n      Project name: pandas\\n      Project version: 2.1.4\\n      C compiler for the host machine: cc (gcc 14.2.0 \"cc (Raspbian 14.2.0-19+rpi1) 14.2.0\")\\n      C linker for the host machine: cc ld.bfd 2.44\\n      C++ compiler for the host machine: c++ (gcc 14.2.0 \"c++ (Raspbian 14.2.0-19+rpi1) 14.2.0\")\\n      C++ linker for the host machine: c++ ld.bfd 2.44\\n      Cython compiler for the host machine: cython (cython 0.29.37)\\n      Host machine cpu family: arm\\n      Host machine cpu: armv7l\\n      Program python found: YES (/opt/app/venv/bin/python)\\n      \\n      ../../pandas/meson.build:1:15: ERROR: Command `/opt/app/venv/bin/python -c \\'\\n      import os\\n      import numpy as np\\n      try:\\n          # Check if include directory is inside the pandas dir\\n          # e.g. a venv created inside the pandas dir\\n          # If so, convert it to a relative path\\n          incdir = os.path.relpath(np.get_include())\\n      except Exception:\\n          incdir = np.get_include()\\n      print(incdir)\\n           \\'` failed with status 1.\\n      \\n      A full log can be found at /tmp/pip-install-lpm0348t/pandas_049cc42ad8234edf931488590a6d6657/.mesonpy-lko771pl/build/meson-logs/meson-log.txt\\n      [end of output]\\n  \\n  note: This error originates from a subprocess, and is likely not a problem with pip.\\nerror: metadata-generation-failed\\n\\n× Encountered error while generating package metadata.\\n╰─> See above for output.\\n\\nnote: This is an issue with the package mentioned above, not pip.\\nhint: See above for details.\\n\\n```\\n\\nTried `main` Branch:\\n```\\nLooking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple\\nCollecting pandas@ git+https://github.com/pandas-dev/pandas@main (from -r requirements.txt (line 4))\\n  Cloning https://github.com/pandas-dev/pandas (to revision main) to /tmp/pip-install-q7i1opum/pandas_0a4fefd97257431fa2c67332ca1aa7e0\\n  Running command git clone --filter=blob:none --quiet https://github.com/pandas-dev/pandas /tmp/pip-install-q7i1opum/pandas_0a4fefd97257431fa2c67332ca1aa7e0\\n  Resolved https://github.com/pandas-dev/pandas to commit 3940df8255ed04db0089e66ce09a4c986b97cac4\\n  Installing build dependencies ... done\\n  Getting requirements to build wheel ... done\\n  Installing backend dependencies ... done\\n  Preparing metadata (pyproject.toml) ... error\\n  error: subprocess-exited-with-error\\n  \\n  × Preparing metadata (pyproject.toml) did not run successfully.\\n  │ exit code: 1\\n  ╰─> [34 lines of output]\\n      + meson setup /tmp/pip-install-q7i1opum/pandas_0a4fefd97257431fa2c67332ca1aa7e0 /tmp/pip-install-q7i1opum/pandas_0a4fefd97257431fa2c67332ca1aa7e0/.mesonpy-nyba67pb -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-q7i1opum/pandas_0a4fefd97257431fa2c67332ca1aa7e0/.mesonpy-nyba67pb/meson-python-native-file.ini\\n      The Meson build system\\n      Version: 1.8.3\\n      Source dir: /tmp/pip-install-q7i1opum/pandas_0a4fefd97257431fa2c67332ca1aa7e0\\n      Build dir: /tmp/pip-install-q7i1opum/pandas_0a4fefd97257431fa2c67332ca1aa7e0/.mesonpy-nyba67pb\\n      Build type: native build\\n      Project name: pandas\\n      Project version: 3.0.0.dev0+2322.g3940df8255\\n      C compiler for the host machine: cc (gcc 14.2.0 \"cc (Raspbian 14.2.0-19+rpi1) 14.2.0\")\\n      C linker for the host machine: cc ld.bfd 2.44\\n      C++ compiler for the host machine: c++ (gcc 14.2.0 \"c++ (Raspbian 14.2.0-19+rpi1) 14.2.0\")\\n      C++ linker for the host machine: c++ ld.bfd 2.44\\n      Cython compiler for the host machine: cython (cython 3.1.3)\\n      Host machine cpu family: arm\\n      Host machine cpu: armv7l\\n      Program python found: YES (/opt/app/venv/bin/python)\\n      Program cython found: YES (/tmp/pip-build-env-es6_6v3v/overlay/bin/cython)\\n      Found pkg-config: YES (/usr/bin/pkg-config) 1.8.1\\n      Run-time dependency python found: YES 3.13\\n      \\n      ../pandas/meson.build:1:15: ERROR: Command `/opt/app/venv/bin/python -c \\'\\n      import os\\n      import numpy as np\\n      try:\\n          # Check if include directory is inside the pandas dir\\n          # e.g. a venv created inside the pandas dir\\n          # If so, convert it to a relative path\\n          incdir = os.path.relpath(np.get_include())\\n      except Exception:\\n          incdir = np.get_include()\\n      print(incdir)\\n           \\'` failed with status 1.\\n      \\n      A full log can be found at /tmp/pip-install-q7i1opum/pandas_0a4fefd97257431fa2c67332ca1aa7e0/.mesonpy-nyba67pb/meson-logs/meson-log.txt\\n      [end of output]\\n  \\n  note: This error originates from a subprocess, and is likely not a problem with pip.\\nerror: metadata-generation-failed\\n\\n× Encountered error while generating package metadata.\\n╰─> See above for output.\\n\\nnote: This is an issue with the package mentioned above, not pip.\\nhint: See above for details.\\n```\\n\\nUnfortunately there is no Log at all. Not even the Root Folder essentially:\\n```\\n(venv) USER@HOST:/opt/app $ ls -l /tmp/pip-install-q7i1opum/pandas_0a4fefd97257431fa2c67332ca1aa7e0/.mesonpy-nyba67pb/meson-logs/meson-log.txt\\nls: cannot access \\'/tmp/pip-install-q7i1opum/pandas_0a4fefd97257431fa2c67332ca1aa7e0/.mesonpy-nyba67pb/meson-logs/meson-log.txt\\': No such file or directory\\n(venv) USER@HOST:/opt/app $ ls -l /tmp/pip-install-q7i1opum\\nls: cannot access \\'/tmp/pip-install-q7i1opum\\': No such file or directory\\n```\\n\\nSimilar story for the other Versions tried (2.1.4 and 2.3.1).\\n\\nSystem Information:\\n- Python 3.13.5\\n\\n`/etc/os-release`:\\n```\\nPRETTY_NAME=\"Raspbian GNU/Linux 13 (trixie)\"\\nNAME=\"Raspbian GNU/Linux\"\\nVERSION_ID=\"13\"\\nVERSION=\"13 (trixie)\"\\nVERSION_CODENAME=trixie\\nDEBIAN_VERSION_FULL=13.0\\nID=raspbian\\nID_LIKE=debian\\nHOME_URL=\"http://www.raspbian.org/\"\\nSUPPORT_URL=\"http://www.raspbian.org/RaspbianForums\"\\nBUG_REPORT_URL=\"http://www.raspbian.org/RaspbianBugs\"\\n```\\n\\n`cat /proc/cpuinfo`:\\n```\\nprocessor\\t: 0\\nmodel name\\t: ARMv7 Processor rev 4 (v7l)\\nBogoMIPS\\t: 76.80\\nFeatures\\t: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 \\nCPU implementer\\t: 0x41\\nCPU architecture: 7\\nCPU variant\\t: 0x0\\nCPU part\\t: 0xd03\\nCPU revision\\t: 4\\n\\nprocessor\\t: 1\\nmodel name\\t: ARMv7 Processor rev 4 (v7l)\\nBogoMIPS\\t: 76.80\\nFeatures\\t: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 \\nCPU implementer\\t: 0x41\\nCPU architecture: 7\\nCPU variant\\t: 0x0\\nCPU part\\t: 0xd03\\nCPU revision\\t: 4\\n\\nprocessor\\t: 2\\nmodel name\\t: ARMv7 Processor rev 4 (v7l)\\nBogoMIPS\\t: 76.80\\nFeatures\\t: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 \\nCPU implementer\\t: 0x41\\nCPU architecture: 7\\nCPU variant\\t: 0x0\\nCPU part\\t: 0xd03\\nCPU revision\\t: 4\\n\\nprocessor\\t: 3\\nmodel name\\t: ARMv7 Processor rev 4 (v7l)\\nBogoMIPS\\t: 76.80\\nFeatures\\t: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 \\nCPU implementer\\t: 0x41\\nCPU architecture: 7\\nCPU variant\\t: 0x0\\nCPU part\\t: 0xd03\\nCPU revision\\t: 4\\n\\nHardware\\t: BCM2835\\nRevision\\t: a02082\\nSerial\\t\\t: 000000003cad014e\\nModel\\t\\t: Raspberry Pi 3 Model B Rev 1.2\\n```\\n\\n\\n`raspinfo`:\\n```\\nSystem Information\\n------------------\\n\\nRaspberry Pi 3 Model B Rev 1.2\\nPRETTY_NAME=\"Raspbian GNU/Linux 13 (trixie)\"\\nNAME=\"Raspbian GNU/Linux\"\\nVERSION_ID=\"13\"\\nVERSION=\"13 (trixie)\"\\n\\nRaspberry Pi reference 2023-10-10\\nGenerated using pi-gen, https://github.com/RPi-Distro/pi-gen, fb56ad562991cf3ae5c96ab50983e1deeaefc7b6, stage2\\n\\nLinux HOST 6.12.34+rpt-rpi-v7 #1 SMP Raspbian 1:6.12.34-1+rpt1 (2025-06-26) armv7l GNU/Linux\\nRevision\\t: a02082\\nSerial\\t\\t: 000000003cad014e\\nModel\\t\\t: Raspberry Pi 3 Model B Rev 1.2\\nThrottled flag  : throttled=0x20000\\nCamera          : supported=0 detected=0, libcamera interfaces=0\\n```', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62146/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62146/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62145', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62145/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62145/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62145/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62145', 'id': 3334809071, 'node_id': 'PR_kwDOAA0YD86kUk9u', 'number': 62145, 'title': 'fix enum typing from _lib', 'user': {'login': 'Dr-Irv', 'id': 15113894, 'node_id': 'MDQ6VXNlcjE1MTEzODk0', 'avatar_url': 'https://avatars.githubusercontent.com/u/15113894?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Dr-Irv', 'html_url': 'https://github.com/Dr-Irv', 'followers_url': 'https://api.github.com/users/Dr-Irv/followers', 'following_url': 'https://api.github.com/users/Dr-Irv/following{/other_user}', 'gists_url': 'https://api.github.com/users/Dr-Irv/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Dr-Irv/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Dr-Irv/subscriptions', 'organizations_url': 'https://api.github.com/users/Dr-Irv/orgs', 'repos_url': 'https://api.github.com/users/Dr-Irv/repos', 'events_url': 'https://api.github.com/users/Dr-Irv/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Dr-Irv/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-19T15:28:47Z', 'updated_at': '2025-08-19T17:54:37Z', 'closed_at': None, 'author_association': 'CONTRIBUTOR', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62145', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62145', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62145.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62145.patch', 'merged_at': None}, 'body': '`mypy` is fixing how they handle `enum` types, and the fix revealed an issue with how we handle them.\\r\\n\\r\\nSee https://github.com/python/mypy/pull/19687#issuecomment-3200527533\\r\\n\\r\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62145/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62145/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62144', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62144/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62144/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62144/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62144', 'id': 3334753694, 'node_id': 'I_kwDOAA0YD87GxE2e', 'number': 62144, 'title': 'BUG / API: setitem on pandas object fails if underlying numpy array is read-only', 'user': {'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [{'id': 2822098, 'node_id': 'MDU6TGFiZWwyODIyMDk4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Indexing', 'name': 'Indexing', 'color': '0b02e1', 'default': False, 'description': 'Related to indexing on series/frames, not to indexes themselves'}, {'id': 35818298, 'node_id': 'MDU6TGFiZWwzNTgxODI5OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/API%20Design', 'name': 'API Design', 'color': 'AD7FA8', 'default': False, 'description': None}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 3, 'created_at': '2025-08-19T15:11:31Z', 'updated_at': '2025-08-19T18:46:50Z', 'closed_at': None, 'author_association': 'MEMBER', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': 'Consider the following example:\\n\\n```python\\n>>> ser = pd.Series(np.asarray(pa.array([1, 2, 3])), copy=False)\\n>>> ser\\n0    1\\n1    2\\n2    3\\ndtype: int64\\n>>> ser.iloc[0] = 10\\n...\\nFile ~/scipy/repos/pandas/pandas/core/internals/blocks.py:1139, in Block.setitem(self, indexer, value)\\n   1137     casted = casted[0, ...]\\n   1138 try:\\n-> 1139     values[indexer] = casted\\n   1140 except (TypeError, ValueError) as err:\\n   1141     if is_list_like(casted):\\n\\nValueError: assignment destination is read-only\\n```\\n\\nHere I create a pandas Series backed by a read-only numpy array somewhat manually through conversion from pyarrow and an explicit `copy=False`, but you can also run into this in certain cases when converting from Arrow-like data to pandas (depending on the exact conversion method). And with CoW we are now returning read-only arrays from `.values` etc, and so this might also become more common in non-Arrow related code.\\n\\nFrom a user perspective, you have a pandas Series, and in general we allow to mutate a Series. **So should this just always work?** (regardless of how the Series was created, which is not necessarily always under the user control)\\n\\nIf this happens, we could automatically copy the array inplace in the Series to let the high-level pandas setitem operation work as expected (at the cost of an unexpected delayed copy, but this is similar as with CoW)\\n\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62144/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62144/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62143', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62143/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62143/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62143/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62143', 'id': 3333226449, 'node_id': 'PR_kwDOAA0YD86kPRbc', 'number': 62143, 'title': 'DOC: Clarify is_scalar docstring to specify scalar vs non-scalar and add Enum example (GH#62063)', 'user': {'login': 'Aniketsy', 'id': 148300120, 'node_id': 'U_kgDOCNbhWA', 'avatar_url': 'https://avatars.githubusercontent.com/u/148300120?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Aniketsy', 'html_url': 'https://github.com/Aniketsy', 'followers_url': 'https://api.github.com/users/Aniketsy/followers', 'following_url': 'https://api.github.com/users/Aniketsy/following{/other_user}', 'gists_url': 'https://api.github.com/users/Aniketsy/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Aniketsy/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Aniketsy/subscriptions', 'organizations_url': 'https://api.github.com/users/Aniketsy/orgs', 'repos_url': 'https://api.github.com/users/Aniketsy/repos', 'events_url': 'https://api.github.com/users/Aniketsy/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Aniketsy/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 1, 'created_at': '2025-08-19T07:22:18Z', 'updated_at': '2025-08-22T06:41:39Z', 'closed_at': None, 'author_association': 'CONTRIBUTOR', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62143', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62143', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62143.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62143.patch', 'merged_at': None}, 'body': '(GH#62063)\\r\\nThis PR updates the docstring for is_scalar to better reflect its actual behavior in pandas.\\r\\n\\r\\nClearly differentiates between values considered scalars and values treated as non-scalars.\\r\\n\\r\\nExplicitly documents that the following are treated as non-scalars\\r\\n     np.ndarray,  list , tuple , pandas.Series.\\r\\n\\r\\nPlease let me know if this fix needs any improvements . I’m open to feedback and happy to make changes based on suggestions.\\r\\nThankyou!\\r\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62143/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62143/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62142', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62142/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62142/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62142/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62142', 'id': 3332198888, 'node_id': 'PR_kwDOAA0YD86kL9Eg', 'number': 62142, 'title': 'DEPR: Categorical with values not present in categories', 'user': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-18T21:30:22Z', 'updated_at': '2025-08-21T20:28:27Z', 'closed_at': None, 'author_association': 'MEMBER', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62142', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62142', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62142.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62142.patch', 'merged_at': None}, 'body': '- [x] closes #40996 \\r\\n- [x] closes #59899\\r\\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\\r\\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\\r\\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\\r\\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\\r\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62142/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62142/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62141', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62141/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62141/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62141/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62141', 'id': 3330046734, 'node_id': 'I_kwDOAA0YD87GfHsO', 'number': 62141, 'title': 'ENH: Consistent `name` property for the iterates in `DataFrameGroupBy`', 'user': {'login': 'FelixBenning', 'id': 29106652, 'node_id': 'MDQ6VXNlcjI5MTA2NjUy', 'avatar_url': 'https://avatars.githubusercontent.com/u/29106652?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/FelixBenning', 'html_url': 'https://github.com/FelixBenning', 'followers_url': 'https://api.github.com/users/FelixBenning/followers', 'following_url': 'https://api.github.com/users/FelixBenning/following{/other_user}', 'gists_url': 'https://api.github.com/users/FelixBenning/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/FelixBenning/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/FelixBenning/subscriptions', 'organizations_url': 'https://api.github.com/users/FelixBenning/orgs', 'repos_url': 'https://api.github.com/users/FelixBenning/repos', 'events_url': 'https://api.github.com/users/FelixBenning/events{/privacy}', 'received_events_url': 'https://api.github.com/users/FelixBenning/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 1741841389, 'node_id': 'MDU6TGFiZWwxNzQxODQxMzg5', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/API%20-%20Consistency', 'name': 'API - Consistency', 'color': 'b60205', 'default': False, 'description': 'Internal Consistency of API/Behavior'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 3, 'created_at': '2025-08-18T10:00:32Z', 'updated_at': '2025-08-20T03:08:22Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': \"### Feature Type\\n\\n- [ ] Adding new functionality to pandas\\n\\n- [x] Changing existing functionality in pandas\\n\\n- [ ] Removing existing functionality in pandas\\n\\n\\n### Problem Description\\n\\nIf a dataframe is grouped by a single column sometimes its `name` is a numeric scalar and sometimes a single element tuple. This should be more consistent.\\n\\nIn the following I will consider the following example dataframe\\n```python\\n>>> df\\n   a  b  c\\n0  1  2  3\\n1  1  5  6\\n2  7  8  9\\n```\\n\\n## Cases where `name` is a scalar\\n\\n- `DataFrameGroupBy.groups`\\n\\n    ```python\\n    >>> print(df.groupby(['a']).groups)\\n    {1: [0, 1], 7: [2]}\\n    ```\\n\\n- `DataFrameGroupBy.apply`\\n\\n    ```python\\n    >>> df.groupby(['a']).apply(lambda x: print(x.name), include_groups=False)\\n    1\\n    7\\n    Empty DataFrame\\n    Columns: []\\n    Index: []\\n    >>> \\n    ```\\n\\n## Cases where `name` is a one element tuple\\n\\n-  `DataFrameGroupBy.__iter__`\\n    ```python\\n    >>> for name, _ in df.groupby(['a']): print(name)\\n    ... \\n    (1,)\\n    (7,)\\n    ```\\n\\n## Documentation\\n\\nIt should perhaps be said that `DataFrameGroupBy.name` is ill documented. But it is not a private property. It seems like the most natural thing to query if you need the information from the columns that you have grouped.\\n\\nThis is especially important, as pandas forces `include_groups=False` in `apply` with a `FutureWarning`/`DeprecationWarning`. So `DataFrameGroupBy.name` seems like the most natural way to reobtain this information now.\\n\\n\\n\\n\\n### Feature Description\\n\\nConsistency in either direction:\\n- PRO SCALAR: It appears that in the majority of cases the `name` is a scalar. Although to be fair I have not checked many cases. This is probably also more intuitive to people that do not think about multiple column groupings\\n\\n- PRO TUPLE: The single element tuple makes this more consistent with the case, where multiple columns are selected.\\n\\n\\n\\n\\n### Additional Context\\n\\n_No response_\", 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62141/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62141/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62139', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62139/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62139/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62139/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62139', 'id': 3329623081, 'node_id': 'PR_kwDOAA0YD86kDXV_', 'number': 62139, 'title': 'BUG: Fix to_csv microsecond inconsistency (#62111)', 'user': {'login': 'prazian', 'id': 10402655, 'node_id': 'MDQ6VXNlcjEwNDAyNjU1', 'avatar_url': 'https://avatars.githubusercontent.com/u/10402655?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/prazian', 'html_url': 'https://github.com/prazian', 'followers_url': 'https://api.github.com/users/prazian/followers', 'following_url': 'https://api.github.com/users/prazian/following{/other_user}', 'gists_url': 'https://api.github.com/users/prazian/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/prazian/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/prazian/subscriptions', 'organizations_url': 'https://api.github.com/users/prazian/orgs', 'repos_url': 'https://api.github.com/users/prazian/repos', 'events_url': 'https://api.github.com/users/prazian/events{/privacy}', 'received_events_url': 'https://api.github.com/users/prazian/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-18T07:58:24Z', 'updated_at': '2025-08-18T14:05:08Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62139', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62139', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62139.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62139.patch', 'merged_at': None}, 'body': '- [x] closes #62111\\r\\n- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\\r\\n- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\\r\\n- [x] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\\r\\n- [x] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\\r\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62139/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62139/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62138', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62138/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62138/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62138/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62138', 'id': 3329292249, 'node_id': 'PR_kwDOAA0YD86kCTSE', 'number': 62138, 'title': 'BUG: Preserve day freq on DatetimeIndex subtraction', 'user': {'login': '23f-1000003', 'id': 154955621, 'node_id': 'U_kgDOCTxvZQ', 'avatar_url': 'https://avatars.githubusercontent.com/u/154955621?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/23f-1000003', 'html_url': 'https://github.com/23f-1000003', 'followers_url': 'https://api.github.com/users/23f-1000003/followers', 'following_url': 'https://api.github.com/users/23f-1000003/following{/other_user}', 'gists_url': 'https://api.github.com/users/23f-1000003/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/23f-1000003/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/23f-1000003/subscriptions', 'organizations_url': 'https://api.github.com/users/23f-1000003/orgs', 'repos_url': 'https://api.github.com/users/23f-1000003/repos', 'events_url': 'https://api.github.com/users/23f-1000003/events{/privacy}', 'received_events_url': 'https://api.github.com/users/23f-1000003/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 1, 'created_at': '2025-08-18T06:05:44Z', 'updated_at': '2025-08-18T06:06:44Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62138', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62138', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62138.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62138.patch', 'merged_at': None}, 'body': '- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\\r\\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\\r\\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\\r\\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\\r\\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\\r\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62138/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62138/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62136', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62136/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62136/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62136/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62136', 'id': 3329159586, 'node_id': 'PR_kwDOAA0YD86kB4hm', 'number': 62136, 'title': 'DOC: Deprecate empty string defaults in DataFrame.join suffixes', 'user': {'login': 'Roline-Stapny', 'id': 29833743, 'node_id': 'MDQ6VXNlcjI5ODMzNzQz', 'avatar_url': 'https://avatars.githubusercontent.com/u/29833743?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Roline-Stapny', 'html_url': 'https://github.com/Roline-Stapny', 'followers_url': 'https://api.github.com/users/Roline-Stapny/followers', 'following_url': 'https://api.github.com/users/Roline-Stapny/following{/other_user}', 'gists_url': 'https://api.github.com/users/Roline-Stapny/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Roline-Stapny/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Roline-Stapny/subscriptions', 'organizations_url': 'https://api.github.com/users/Roline-Stapny/orgs', 'repos_url': 'https://api.github.com/users/Roline-Stapny/repos', 'events_url': 'https://api.github.com/users/Roline-Stapny/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Roline-Stapny/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-18T04:55:03Z', 'updated_at': '2025-08-22T00:01:27Z', 'closed_at': None, 'author_association': 'CONTRIBUTOR', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62136', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62136', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62136.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62136.patch', 'merged_at': None}, 'body': '- [X] closes [#61294 ](https://github.com/pandas-dev/pandas/issues/61294)\\r\\n- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\\r\\n- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\\r\\n- [X] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\\r\\n- [X] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\\r\\n\\r\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62136/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62136/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62135', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62135/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62135/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62135/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62135', 'id': 3328849299, 'node_id': 'PR_kwDOAA0YD86kA2PF', 'number': 62135, 'title': 'BUG: Fix groupby.apply() dropping _metadata from subclassed DataFrame', 'user': {'login': 'MengAiDev', 'id': 202287492, 'node_id': 'U_kgDODA6phA', 'avatar_url': 'https://avatars.githubusercontent.com/u/202287492?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/MengAiDev', 'html_url': 'https://github.com/MengAiDev', 'followers_url': 'https://api.github.com/users/MengAiDev/followers', 'following_url': 'https://api.github.com/users/MengAiDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/MengAiDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/MengAiDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/MengAiDev/subscriptions', 'organizations_url': 'https://api.github.com/users/MengAiDev/orgs', 'repos_url': 'https://api.github.com/users/MengAiDev/repos', 'events_url': 'https://api.github.com/users/MengAiDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/MengAiDev/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 3, 'created_at': '2025-08-18T01:09:31Z', 'updated_at': '2025-08-20T03:15:52Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62135', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62135', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62135.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62135.patch', 'merged_at': None}, 'body': 'When extending pandas.DataFrame by subclassing, most operations preserve the _metadata attributes. This fix ensures that groupby.apply() also preserves these fields, making it consistent with other groupby operations like groupby.sum().\\r\\n\\r\\nFixes #62134', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62135/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62135/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62134', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62134/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62134/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62134/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62134', 'id': 3328402711, 'node_id': 'I_kwDOAA0YD87GY2UX', 'number': 62134, 'title': 'BUG: groupby.apply() drops _metadata from subclassed DataFrame', 'user': {'login': 'JBGreisman', 'id': 6944142, 'node_id': 'MDQ6VXNlcjY5NDQxNDI=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6944142?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/JBGreisman', 'html_url': 'https://github.com/JBGreisman', 'followers_url': 'https://api.github.com/users/JBGreisman/followers', 'following_url': 'https://api.github.com/users/JBGreisman/following{/other_user}', 'gists_url': 'https://api.github.com/users/JBGreisman/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/JBGreisman/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/JBGreisman/subscriptions', 'organizations_url': 'https://api.github.com/users/JBGreisman/orgs', 'repos_url': 'https://api.github.com/users/JBGreisman/repos', 'events_url': 'https://api.github.com/users/JBGreisman/events{/privacy}', 'received_events_url': 'https://api.github.com/users/JBGreisman/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1539579994, 'node_id': 'MDU6TGFiZWwxNTM5NTc5OTk0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/metadata', 'name': 'metadata', 'color': '56efc9', 'default': False, 'description': '_metadata, .attrs'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-17T15:03:32Z', 'updated_at': '2025-08-17T15:37:00Z', 'closed_at': None, 'author_association': 'CONTRIBUTOR', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': '### Pandas version checks\\n\\n- [x] I have checked that this issue has not already been reported.\\n\\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\\n\\n- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\\n\\n\\n### Reproducible Example\\n\\n```python\\nimport pandas._testing as tm\\nimport numpy as np\\n\\nsubdf = tm.SubclassedDataFrame(\\n    {\"X\": [1, 1, 2, 2, 3], \"Y\": np.arange(0, 5), \"Z\": np.arange(10, 15)}\\n)\\nsubdf.testattr = \"test\"\\n\\n# Calculate groupby-sum in two ways: one preserves metadata, one does not\\nexpected = subdf.groupby(\"X\").sum()\\nresult = subdf.groupby(\"X\").apply(np.sum, axis=0, include_groups=False)\\n\\n# Both dataframes have equivalent content\\ntm.assert_frame_equal(result, expected)\\n\\nprint(expected.testattr)    # prints \"test\"\\nprint(result.testattr)      # raises AttributeError\\n```\\n\\n### Issue Description\\n\\nWhen extending the `pandas.DataFrame` by subclassing, most operations preserve the `_metadata` attributes. This is not the case for `groupby.apply()`, after which the `_metadata` fields are dropped. I think this is unintended behavior, because an equivalent call using a built-in groupby method (such as `groupby.mean()`) does preserve the fields. \\n\\n### Expected Behavior\\n\\n```python\\nimport pandas._testing as tm\\nimport numpy as np\\n\\nsubdf = tm.SubclassedDataFrame(\\n    {\"X\": [1, 1, 2, 2, 3], \"Y\": np.arange(0, 5), \"Z\": np.arange(10, 15)}\\n)\\nsubdf.testattr = \"test\"\\nresult = subdf.groupby(\"X\").apply(np.sum, axis=0, include_groups=False)\\n\\nassert result.testattr == \"test\"   # attribute should be preserved after groupby-apply\\n```\\n\\n### Installed Versions\\n\\n<details>\\n\\nINSTALLED VERSIONS\\n------------------\\ncommit                : c888af6d0bb674932007623c0867e1fbd4bdc2c6\\npython                : 3.12.11\\npython-bits           : 64\\nOS                    : Darwin\\nOS-release            : 24.6.0\\nVersion               : Darwin Kernel Version 24.6.0: Mon Jul 14 11:30:51 PDT 2025; root:xnu-11417.140.69~1/RELEASE_ARM64_T8112\\nmachine               : arm64\\nprocessor             : arm\\nbyteorder             : little\\nLC_ALL                : None\\nLANG                  : en_US.UTF-8\\nLOCALE                : en_US.UTF-8\\n\\npandas                : 2.3.1\\nnumpy                 : 2.2.6\\npytz                  : 2025.2\\ndateutil              : 2.9.0.post0\\npip                   : 25.1\\nCython                : 3.1.3\\nsphinx                : 8.1.3\\nIPython               : 9.4.0\\nadbc-driver-postgresql: None\\nadbc-driver-sqlite    : None\\nbs4                   : 4.13.4\\nblosc                 : None\\nbottleneck            : 1.5.0\\ndataframe-api-compat  : None\\nfastparquet           : 2024.11.0\\nfsspec                : 2025.7.0\\nhtml5lib              : 1.1\\nhypothesis            : 6.138.2\\ngcsfs                 : 2025.7.0\\njinja2                : 3.1.6\\nlxml.etree            : 6.0.0\\nmatplotlib            : 3.10.5\\nnumba                 : 0.61.2\\nnumexpr               : 2.11.0\\nodfpy                 : None\\nopenpyxl              : 3.1.5\\npandas_gbq            : None\\npsycopg2              : 2.9.10\\npymysql               : 1.4.6\\npyarrow               : 21.0.0\\npyreadstat            : 1.3.1\\npytest                : 8.4.1\\npython-calamine       : None\\npyxlsb                : 1.0.10\\ns3fs                  : 2025.7.0\\nscipy                 : 1.16.1\\nsqlalchemy            : 2.0.43\\ntables                : 3.10.2\\ntabulate              : 0.9.0\\nxarray                : 2025.8.0\\nxlrd                  : 2.0.2\\nxlsxwriter            : 3.2.5\\nzstandard             : 0.23.0\\ntzdata                : 2025.2\\nqtpy                  : None\\npyqt5                 : None\\n\\n\\n</details>\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62134/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62134/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62131', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62131/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62131/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62131/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62131', 'id': 3327046500, 'node_id': 'PR_kwDOAA0YD86j7hJX', 'number': 62131, 'title': 'ENH: Enable destination aware scope for dataset attributes metadata propagation copy routines', 'user': {'login': 'dangreb', 'id': 45799375, 'node_id': 'MDQ6VXNlcjQ1Nzk5Mzc1', 'avatar_url': 'https://avatars.githubusercontent.com/u/45799375?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/dangreb', 'html_url': 'https://github.com/dangreb', 'followers_url': 'https://api.github.com/users/dangreb/followers', 'following_url': 'https://api.github.com/users/dangreb/following{/other_user}', 'gists_url': 'https://api.github.com/users/dangreb/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/dangreb/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/dangreb/subscriptions', 'organizations_url': 'https://api.github.com/users/dangreb/orgs', 'repos_url': 'https://api.github.com/users/dangreb/repos', 'events_url': 'https://api.github.com/users/dangreb/events{/privacy}', 'received_events_url': 'https://api.github.com/users/dangreb/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 7, 'created_at': '2025-08-16T08:40:19Z', 'updated_at': '2025-08-20T23:28:52Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'draft': True, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62131', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62131', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62131.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62131.patch', 'merged_at': None}, 'body': \"As noted in project docstrings, **NDFrame.attrs** is meant to store properties related to the dataset. Therefore it should be important that during  propagation to derived datasets, copy routines can have access to the destination object, to witch it's new formulation will then refeer to.\\r\\n\\r\\n- A lean and isolated fix manages to acomplish this, by forwarding the instance via deepcopy's **memo** payload dict. \\r\\n- The key for the dict entry will be **builtins.id()** of the nwe dataset, complying with mandatory **int** tipification. \\r\\n- Implemented for both NDFrame heirs and concat/merge scenarios. Not relevant for Indexes as it seeems.\\r\\n\\r\\nI'll open as draft before it can be deemed admissible.\", 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62131/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62131/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62130', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62130/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62130/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62130/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62130', 'id': 3326937635, 'node_id': 'PR_kwDOAA0YD86j7Los', 'number': 62130, 'title': 'Resolved issue 62094', 'user': {'login': 'saw1998', 'id': 42498505, 'node_id': 'MDQ6VXNlcjQyNDk4NTA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/42498505?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/saw1998', 'html_url': 'https://github.com/saw1998', 'followers_url': 'https://api.github.com/users/saw1998/followers', 'following_url': 'https://api.github.com/users/saw1998/following{/other_user}', 'gists_url': 'https://api.github.com/users/saw1998/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/saw1998/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/saw1998/subscriptions', 'organizations_url': 'https://api.github.com/users/saw1998/orgs', 'repos_url': 'https://api.github.com/users/saw1998/repos', 'events_url': 'https://api.github.com/users/saw1998/events{/privacy}', 'received_events_url': 'https://api.github.com/users/saw1998/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-16T06:07:46Z', 'updated_at': '2025-08-17T21:54:05Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62130', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62130', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62130.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62130.patch', 'merged_at': None}, 'body': 'Using default frequency as difference between two TimeDeltas\\r\\n\\r\\n- [ ] closes #xxxx (Replace xxxx with the GitHub issue number)\\r\\n- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature\\r\\n- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).\\r\\n- [ ] Added [type annotations](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#type-hints) to new arguments/methods/functions.\\r\\n- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.\\r\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62130/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62130/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62129', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62129/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62129/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62129/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62129', 'id': 3326707889, 'node_id': 'I_kwDOAA0YD87GSYix', 'number': 62129, 'title': 'REF/API: Move ArrowDtype(pa.foo_string()) into StringDtype(...)', 'user': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 7, 'created_at': '2025-08-16T01:28:29Z', 'updated_at': '2025-08-18T16:34:19Z', 'closed_at': None, 'author_association': 'MEMBER', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': 'This came up when reviewing #62118.  There are too many StringDtypes and FooStringArrays.  Apparently pd.ArrowDtype can accommodate some specific types of pyarrow strings that `StringDtype(storage=\"pyarrow\")` cannot.  I propose that we\\n\\n1) Extend pd.StringDtype (and ArrowStringArray) to allow it to support the specific variants of pyarrow strings we want to support\\n2) Deprecate support for those in ArrowDtype/ArrowEA, moving users to the StringArray.\\n3) Try to refactor all the FooStringArray variants down to just one StringArray.', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62129/reactions', 'total_count': 1, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 1, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62129/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62121', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62121/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62121/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62121/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62121', 'id': 3324839717, 'node_id': 'I_kwDOAA0YD87GLQcl', 'number': 62121, 'title': 'BUG: Addition of __set_module__ breaks PyCharm PyDev debugger functionalities', 'user': {'login': 'dangreb', 'id': 45799375, 'node_id': 'MDQ6VXNlcjQ1Nzk5Mzc1', 'avatar_url': 'https://avatars.githubusercontent.com/u/45799375?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/dangreb', 'html_url': 'https://github.com/dangreb', 'followers_url': 'https://api.github.com/users/dangreb/followers', 'following_url': 'https://api.github.com/users/dangreb/following{/other_user}', 'gists_url': 'https://api.github.com/users/dangreb/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/dangreb/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/dangreb/subscriptions', 'organizations_url': 'https://api.github.com/users/dangreb/orgs', 'repos_url': 'https://api.github.com/users/dangreb/repos', 'events_url': 'https://api.github.com/users/dangreb/events{/privacy}', 'received_events_url': 'https://api.github.com/users/dangreb/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/102', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102/labels', 'id': 9021906, 'node_id': 'MI_kwDOAA0YD84AianS', 'number': 102, 'title': '3.0', 'description': '', 'creator': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'open_issues': 38, 'closed_issues': 1963, 'state': 'open', 'created_at': '2023-02-08T18:16:49Z', 'updated_at': '2025-08-22T16:51:08Z', 'due_on': None, 'closed_at': None}, 'comments': 2, 'created_at': '2025-08-15T09:36:01Z', 'updated_at': '2025-08-15T17:21:50Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': '### Pandas version checks\\n\\n- [x] I have checked that this issue has not already been reported.\\n\\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\\n\\n- [x] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\\n\\n\\n### Reproducible Example\\n\\n```python\\nimport sys\\n\\nimport pandas as pd\\n\\n# Envo. must have \"pydev-pycharm\", install with:\\n# pip install pydevd-pycharm\\nfrom _pydevd_bundle.pydevd_user_type_renderers import UserTypeRenderer, parse_set_type_renderers_message\\nfrom _pydevd_bundle.pydevd_user_type_renderers_utils import try_get_type_renderer_for_var\\n\\n# Payload extrated from PyCharm\\'s PyDev runtime. Contains the payload provided by the IDE\\'s Java side,\\n# built from a sample customizing. It contains two \"Custom Views\", one for builtins.object (working fine)\\n# and one for pandas.DataFrame (not working).\\nSAMPLE_TR_CONFIG_MESSAGE = \"\"\"RENDERERS\\t9\\tbuiltins.object\\tbuiltins.object\\tobject\\tC:/Program Files/JetBrains/PyCharm 2025.2.0.1/plugins/python-ce/helpers/typeshed/stdlib/builtins.pyi\\t1\\t0\\t\"DBG:\"+ type(self).__name__\\t1\\t0\\t9\\tpandas.DataFrame\\tpandas.DataFrame\\tpandas.core.frame.DataFrame\\t<PYTHON_PATH>/Lib/site-packages/pandas-stubs/core/frame.pyi\\t0\\t0\\t\"DBG:\"+ type(self).__name__\\t1\\t0\"\"\"\\n\\ndef main() -> None:\\n    pass\\n    renderers = parse_set_type_renderers_message(SAMPLE_TR_CONFIG_MESSAGE)\\n    df = pd.DataFrame({\"dmmy\": map(float,range(8))})\\n    obj = object()\\n\\n    object_type_renderer: UserTypeRenderer = try_get_type_renderer_for_var(obj, renderers)\\n    dataframe_type_renderer: UserTypeRenderer = try_get_type_renderer_for_var(df, renderers)\\n\\n    print(f\\'Type Renderer for builtins.object | {object_type_renderer}\\')\\n    print(f\\'Type Renderer for pandas.DataFrame | {dataframe_type_renderer}\\')\\n\\n    # Should Output\\n    \"\"\"\\n    Type Renderer for builtins.object | <_pydevd_bundle.pydevd_user_type_renderers.UserTypeRenderer object at 0x0000048DDD0B2950>\\n    Type Renderer for pandas.DataFrame | None\\n    \"\"\"\\n\\n\\nif __name__ in {\"__main__\", \"__mp_main__\"}:\\n    sys.exit(main())\\n```\\n\\n### Issue Description\\n\\nAs described at the referenced comment at \"ENH: 55178\": \\n\\nThe addition of the decorator set_module for DataFrames and Series, as far as i managed to verify, seems to be causing issues in PyCharm\\'s Type Renderers functionality. When a Custom Data View is created at the IDE, we need to inform the target type, and the settings engine will validate the input against stubs and save the full qualified name it gets from them! Since no such abreviation is in place at the stubs, it will record \"pandas.core.frame.DataFrame\" as the qualified name.\\n\\nThen when JetBrains\\'s PyDev fork, that is base for PyCharm debugger, search for Type Renderers customized for the DataFrame, it compares the abreviated \"qualname\" from runtime (basically f\\'{type(obj)module}.{type(obj)name}\\' that will make for \"andas.DataFrame\") with the one he recorded from the customizing based on the stubs (that will be \"pandas.core.frame.DataFrame\").\\n\\nThere\\'s also some hard-codes for pandas.core.frame.DataFrame and pandas.core.frame.Series at a \"Table Provider\" routine, used to determine PyCharm\\'s \"Data View\" tool engine for pandas\\'s DataFrames and Series, but that i believe should be addressed over there?\\n\\nThanks!\\n\\n### Expected Behavior\\n\\nConsidering the reproducible provided, \"pydevd-pycharm\" should provide a \"UserTypeRenderer\" object from the call performed to \"try_get_type_renderer_for_var\", since it was configured correctly at PyCharm\\'s Type Rederers settings.\\n\\n### Installed Versions\\n\\n<details>\\n\\nNone\\n\\n</details>\\n\\nFor some reason \"show_versions\" return None. I identified this issue while experimenting with pandas release provided at the [scientific nightly conda channel](https://anaconda.org/scientific-python-nightly-wheels/), where we have a pandas 3.0.0 release.', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62121/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62121/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62118', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62118/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62118/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62118/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62118', 'id': 3324748731, 'node_id': 'PR_kwDOAA0YD86j0KLD', 'number': 62118, 'title': 'Switch default string storage from python to pyarrow (if installed) also for NA-variant of the StringDtype', 'user': {'login': 'jorisvandenbossche', 'id': 1020496, 'node_id': 'MDQ6VXNlcjEwMjA0OTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/1020496?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jorisvandenbossche', 'html_url': 'https://github.com/jorisvandenbossche', 'followers_url': 'https://api.github.com/users/jorisvandenbossche/followers', 'following_url': 'https://api.github.com/users/jorisvandenbossche/following{/other_user}', 'gists_url': 'https://api.github.com/users/jorisvandenbossche/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jorisvandenbossche/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jorisvandenbossche/subscriptions', 'organizations_url': 'https://api.github.com/users/jorisvandenbossche/orgs', 'repos_url': 'https://api.github.com/users/jorisvandenbossche/repos', 'events_url': 'https://api.github.com/users/jorisvandenbossche/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jorisvandenbossche/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [{'id': 57522093, 'node_id': 'MDU6TGFiZWw1NzUyMjA5Mw==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Strings', 'name': 'Strings', 'color': '5319e7', 'default': False, 'description': 'String extension data type and string data'}, {'id': 1817503692, 'node_id': 'MDU6TGFiZWwxODE3NTAzNjky', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/NA%20-%20MaskedArrays', 'name': 'NA - MaskedArrays', 'color': '8cc645', 'default': False, 'description': 'Related to pd.NA and nullable extension arrays'}], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': {'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/102', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/102/labels', 'id': 9021906, 'node_id': 'MI_kwDOAA0YD84AianS', 'number': 102, 'title': '3.0', 'description': '', 'creator': {'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'open_issues': 38, 'closed_issues': 1963, 'state': 'open', 'created_at': '2023-02-08T18:16:49Z', 'updated_at': '2025-08-22T16:51:08Z', 'due_on': None, 'closed_at': None}, 'comments': 0, 'created_at': '2025-08-15T08:59:32Z', 'updated_at': '2025-08-16T07:25:12Z', 'closed_at': None, 'author_association': 'MEMBER', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62118', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62118', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62118.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62118.patch', 'merged_at': None}, 'body': 'Closes https://github.com/pandas-dev/pandas/issues/60287\\r\\n\\r\\n(need to add whatsnew)', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62118/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62118/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62117', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62117/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62117/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62117/events', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62117', 'id': 3324694311, 'node_id': 'PR_kwDOAA0YD86jz-vk', 'number': 62117, 'title': 'fix(dtypes): ensure consistent behavior of is_string_dtype for Categorical', 'user': {'login': 'MengAiDev', 'id': 202287492, 'node_id': 'U_kgDODA6phA', 'avatar_url': 'https://avatars.githubusercontent.com/u/202287492?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/MengAiDev', 'html_url': 'https://github.com/MengAiDev', 'followers_url': 'https://api.github.com/users/MengAiDev/followers', 'following_url': 'https://api.github.com/users/MengAiDev/following{/other_user}', 'gists_url': 'https://api.github.com/users/MengAiDev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/MengAiDev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/MengAiDev/subscriptions', 'organizations_url': 'https://api.github.com/users/MengAiDev/orgs', 'repos_url': 'https://api.github.com/users/MengAiDev/repos', 'events_url': 'https://api.github.com/users/MengAiDev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/MengAiDev/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [], 'state': 'open', 'locked': False, 'assignee': None, 'assignees': [], 'milestone': None, 'comments': 0, 'created_at': '2025-08-15T08:30:37Z', 'updated_at': '2025-08-15T08:30:37Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'draft': False, 'pull_request': {'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/62117', 'html_url': 'https://github.com/pandas-dev/pandas/pull/62117', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/62117.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/62117.patch', 'merged_at': None}, 'body': '\\r\\n- Handle Categorical series and CategoricalDtype consistently in is_string_dtype\\r\\n- Add tests to verify consistent results for various Categorical scenarios\\r\\n\\r\\nFix: #62109 ', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62117/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62117/timeline', 'performed_via_github_app': None, 'state_reason': None}, {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62111', 'repository_url': 'https://api.github.com/repos/pandas-dev/pandas', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62111/labels{/name}', 'comments_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62111/comments', 'events_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62111/events', 'html_url': 'https://github.com/pandas-dev/pandas/issues/62111', 'id': 3324079951, 'node_id': 'I_kwDOAA0YD87GIW9P', 'number': 62111, 'title': 'BUG: to_csv uses inconsistent microsecond format for datetimes with timezones', 'user': {'login': 'insperatum', 'id': 3738275, 'node_id': 'MDQ6VXNlcjM3MzgyNzU=', 'avatar_url': 'https://avatars.githubusercontent.com/u/3738275?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/insperatum', 'html_url': 'https://github.com/insperatum', 'followers_url': 'https://api.github.com/users/insperatum/followers', 'following_url': 'https://api.github.com/users/insperatum/following{/other_user}', 'gists_url': 'https://api.github.com/users/insperatum/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/insperatum/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/insperatum/subscriptions', 'organizations_url': 'https://api.github.com/users/insperatum/orgs', 'repos_url': 'https://api.github.com/users/insperatum/repos', 'events_url': 'https://api.github.com/users/insperatum/events{/privacy}', 'received_events_url': 'https://api.github.com/users/insperatum/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'labels': [{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}], 'state': 'open', 'locked': False, 'assignee': {'login': 'prazian', 'id': 10402655, 'node_id': 'MDQ6VXNlcjEwNDAyNjU1', 'avatar_url': 'https://avatars.githubusercontent.com/u/10402655?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/prazian', 'html_url': 'https://github.com/prazian', 'followers_url': 'https://api.github.com/users/prazian/followers', 'following_url': 'https://api.github.com/users/prazian/following{/other_user}', 'gists_url': 'https://api.github.com/users/prazian/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/prazian/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/prazian/subscriptions', 'organizations_url': 'https://api.github.com/users/prazian/orgs', 'repos_url': 'https://api.github.com/users/prazian/repos', 'events_url': 'https://api.github.com/users/prazian/events{/privacy}', 'received_events_url': 'https://api.github.com/users/prazian/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}, 'assignees': [{'login': 'prazian', 'id': 10402655, 'node_id': 'MDQ6VXNlcjEwNDAyNjU1', 'avatar_url': 'https://avatars.githubusercontent.com/u/10402655?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/prazian', 'html_url': 'https://github.com/prazian', 'followers_url': 'https://api.github.com/users/prazian/followers', 'following_url': 'https://api.github.com/users/prazian/following{/other_user}', 'gists_url': 'https://api.github.com/users/prazian/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/prazian/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/prazian/subscriptions', 'organizations_url': 'https://api.github.com/users/prazian/orgs', 'repos_url': 'https://api.github.com/users/prazian/repos', 'events_url': 'https://api.github.com/users/prazian/events{/privacy}', 'received_events_url': 'https://api.github.com/users/prazian/received_events', 'type': 'User', 'user_view_type': 'public', 'site_admin': False}], 'milestone': None, 'comments': 2, 'created_at': '2025-08-15T01:48:25Z', 'updated_at': '2025-08-18T14:07:32Z', 'closed_at': None, 'author_association': 'NONE', 'type': None, 'active_lock_reason': None, 'sub_issues_summary': {'total': 0, 'completed': 0, 'percent_completed': 0}, 'issue_dependencies_summary': {'blocked_by': 0, 'total_blocked_by': 0, 'blocking': 0, 'total_blocking': 0}, 'body': '### Pandas version checks\\n\\n- [x] I have checked that this issue has not already been reported.\\n\\n- [x] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.\\n\\n- [ ] I have confirmed this bug exists on the [main branch](https://pandas.pydata.org/docs/dev/getting_started/install.html#installing-the-development-version-of-pandas) of pandas.\\n\\n\\n### Reproducible Example\\n\\n```python\\nimport pandas as pd\\nfrom datetime import datetime, timezone\\n\\n# Saving and loading without timezones (works fine)\\ndf = pd.DataFrame({\\n    \\'timestamp\\': [\\n        datetime(2025, 8, 14, 12, 34, 56, 0), # No microseconds\\n        datetime(2025, 8, 14, 12, 34, 56, 1)  # With microseconds\\n    ]\\n})\\ndf.to_csv(\\'test.csv\\', index=False)\\n## == test.csv == ##\\n# timestamp\\n# 2025-08-14 12:34:56.000000\\n# 2025-08-14 12:34:56.000001\\n####################\\ndf2 = pd.read_csv(\"test.csv\", parse_dates=[\"timestamp\"])\\nprint(df2.dtypes[\"timestamp\"]) # datetime64[ns]\\n\\n\\n# Saving and loading with timezones (broken)\\ndf = pd.DataFrame({\\n    \\'timestamp\\': [\\n        datetime(2025, 8, 14, 12, 34, 56, 0, tzinfo=timezone.utc), # No microseconds\\n        datetime(2025, 8, 14, 12, 34, 56, 1, tzinfo=timezone.utc)  # With microseconds\\n    ]\\n})\\n## == test.csv == ##\\n# timestamp\\n# 2025-08-14 12:34:56+00:00\\n# 2025-08-14 12:34:56.000001+00:00\\n####################\\ndf.to_csv(\\'test.csv\\', index=False)\\ndf2 = pd.read_csv(\"test.csv\", parse_dates=[\"timestamp\"])\\nprint(df2.dtypes[\"timestamp\"]) # object\\n```\\n\\n### Issue Description\\n\\nWhen saving a datetime column _with timezones_ to a csv, pandas uses an inconsistent format across entries depending on whether the microseconds is zero or nonzero. This means that pandas then fails to parse that column when reading in the same file.\\n\\n### Expected Behavior\\n\\nThe save behavior for dates with timezones should match the behavior for dates without timezones in this case: i.e. use a consistent datetime format that includes microseconds for all rows.\\n\\n### Installed Versions\\n\\n<details>\\n\\nINSTALLED VERSIONS\\n------------------\\ncommit                : c888af6d0bb674932007623c0867e1fbd4bdc2c6\\npython                : 3.13.5\\npython-bits           : 64\\nOS                    : Darwin\\nOS-release            : 24.3.0\\nVersion               : Darwin Kernel Version 24.3.0: Thu Jan  2 20:24:22 PST 2025; root:xnu-11215.81.4~3/RELEASE_ARM64_T6041\\nmachine               : arm64\\nprocessor             : arm\\nbyteorder             : little\\nLC_ALL                : None\\nLANG                  : en_US.UTF-8\\nLOCALE                : en_US.UTF-8\\n\\npandas                : 2.3.1\\nnumpy                 : 2.3.2\\npytz                  : 2025.2\\ndateutil              : 2.9.0.post0\\npip                   : 25.2\\nCython                : None\\nsphinx                : None\\nIPython               : None\\nadbc-driver-postgresql: None\\nadbc-driver-sqlite    : None\\nbs4                   : None\\nblosc                 : None\\nbottleneck            : None\\ndataframe-api-compat  : None\\nfastparquet           : None\\nfsspec                : None\\nhtml5lib              : None\\nhypothesis            : None\\ngcsfs                 : None\\njinja2                : None\\nlxml.etree            : None\\nmatplotlib            : None\\nnumba                 : None\\nnumexpr               : None\\nodfpy                 : None\\nopenpyxl              : None\\npandas_gbq            : None\\npsycopg2              : None\\npymysql               : None\\npyarrow               : None\\npyreadstat            : None\\npytest                : None\\npython-calamine       : None\\npyxlsb                : None\\ns3fs                  : None\\nscipy                 : None\\nsqlalchemy            : None\\ntables                : None\\ntabulate              : None\\nxarray                : None\\nxlrd                  : None\\nxlsxwriter            : None\\nzstandard             : None\\ntzdata                : 2025.2\\nqtpy                  : None\\npyqt5                 : None\\n\\n</details>\\n', 'closed_by': None, 'reactions': {'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62111/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}, 'timeline_url': 'https://api.github.com/repos/pandas-dev/pandas/issues/62111/timeline', 'performed_via_github_app': None, 'state_reason': None}]\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'NoneType' object has no attribute 'head'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[9], line 2\u001b[0m\n\u001b[1;32m      1\u001b[0m data \u001b[38;5;241m=\u001b[39m test_resp\u001b[38;5;241m.\u001b[39mjson()\n\u001b[0;32m----> 2\u001b[0m \u001b[38;5;28;43mprint\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mdata\u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mhead\u001b[49m()\n",
      "\u001b[0;31mAttributeError\u001b[0m: 'NoneType' object has no attribute 'head'"
     ]
    }
   ],
   "source": [
    "data = test_resp.json()\n",
    "print(data)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
